server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.51.73:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Hx947769582..
    type: com.alibaba.druid.pool.DruidDataSource